# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 490512282cfc17403f6b4da5e6b5a8967ba268bf7664e9cd8d3930ae69a06c027fc9dec6a48c4ed13d4405e02ed5b74c6567e05e48850fc7b175c468a7c7b101

test:
  secret_key_base: 721984ff53cf01bf8e6cb8f77121664e76cc56115560de3567665444713bfa8787fde06cb99999df3e3de4b1415ff5f84234340cb9fabaae7316003dcd589492

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
